import { MigrationInterface, QueryRunner } from "typeorm";

export class Final1761415160940 implements MigrationInterface {
    name = 'Final1761415160940'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "grades" DROP CONSTRAINT "FK_004fc3bfe751aeaf87f927b4a8c"`);
        await queryRunner.query(`CREATE TYPE "public"."persons_document_type_enum" AS ENUM('dni', 'passport', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."persons_gender_enum" AS ENUM('MALE', 'FEMALE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."persons_material_status_enum" AS ENUM('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED')`);
        await queryRunner.query(`CREATE TABLE "persons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "document_type" "public"."persons_document_type_enum" NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "birth_date" date NOT NULL, "gender" "public"."persons_gender_enum" NOT NULL, "birth_place" character varying(50) NOT NULL, "nationality" character varying(100) NOT NULL, "address" character varying(20) NOT NULL, "district" character varying(15) NOT NULL, "province" character varying(15) NOT NULL, "department" character varying(15) NOT NULL, "phone" character varying(15) NOT NULL, "mobile" character varying(100) NOT NULL, "email" character varying(100) NOT NULL, "photo_url" character varying(255) NOT NULL, "material_status" "public"."persons_material_status_enum" NOT NULL, CONSTRAINT "UQ_e022ed149591249aa8641e0e282" UNIQUE ("birth_place"), CONSTRAINT "UQ_5aa74853d2135e6078ea8d55c05" UNIQUE ("address"), CONSTRAINT "UQ_b17cd2cfac02400e9af4fb45572" UNIQUE ("district"), CONSTRAINT "UQ_161e950cfa90bf1aecdc8e34db1" UNIQUE ("province"), CONSTRAINT "UQ_daf1828c724e693c9cff725c075" UNIQUE ("department"), CONSTRAINT "UQ_6545fa46b808c5870a6b27a3adf" UNIQUE ("phone"), CONSTRAINT "UQ_68b2f79ca1ccae0180cdd5ff9f6" UNIQUE ("mobile"), CONSTRAINT "UQ_928155276ca8852f3c440cc2b2c" UNIQUE ("email"), CONSTRAINT "PK_74278d8812a049233ce41440ac7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "institutions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "name" character varying(100) NOT NULL, "modular_code" character varying(50) NOT NULL, "management_type" character varying(50) NOT NULL, "ugel" character varying(50) NOT NULL, "dre" character varying(50) NOT NULL, "principal" character varying(50) NOT NULL, "address" character varying(100) NOT NULL, "district" character varying(50) NOT NULL, "province" character varying(50) NOT NULL, "department" character varying(50) NOT NULL, "phone" character varying(50) NOT NULL, "email" character varying(100) NOT NULL, "status" character varying(20) NOT NULL, "logo_url" character varying(255) NOT NULL, "description" text NOT NULL, CONSTRAINT "UQ_c9765650d133f11bede43b347db" UNIQUE ("modular_code"), CONSTRAINT "PK_0be7539dcdba335470dc05e9690" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."students_student_type_enum" AS ENUM('regular', 'irregular', 'external')`);
        await queryRunner.query(`CREATE TYPE "public"."students_status_enum" AS ENUM('active', 'inactive', 'graduated', 'dropped_out')`);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "student_code" character varying(100) NOT NULL, "student_type" "public"."students_student_type_enum" NOT NULL, "religion" character varying(100) NOT NULL, "native_language" character varying(100) NOT NULL, "has_disability" boolean NOT NULL DEFAULT false, "health_issues" character varying(100) array NOT NULL, "insunrance_number" character varying(100) NOT NULL, "blood_type" character varying(10) NOT NULL, "allergies" character varying(255) NOT NULL, "medical_conditions" text NOT NULL, "admision_date" date NOT NULL, "withdrawal_date" date, "withdrawal_reason" text NOT NULL, "status" "public"."students_status_enum" NOT NULL, "institution_id" uuid, "person_id" uuid, CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."enrollments_enrollment_type_enum" AS ENUM('new', 'returning', 'transfer')`);
        await queryRunner.query(`CREATE TYPE "public"."enrollments_status_enum" AS ENUM('enrolled', 'completed', 'dropped', 'graduated')`);
        await queryRunner.query(`CREATE TABLE "enrollments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "code" character varying(20) NOT NULL, "enrollment_date" date NOT NULL, "enrollment_type" "public"."enrollments_enrollment_type_enum" NOT NULL, "status" "public"."enrollments_status_enum" NOT NULL, "order_number" integer NOT NULL, "observations" text, "previus_school" character varying(100) NOT NULL, "previous_grade" character varying(20) NOT NULL, "previus_year" integer NOT NULL, "previus_average" double precision NOT NULL, "is_repeating" boolean NOT NULL DEFAULT false, "has_special_needs" boolean NOT NULL DEFAULT false, "has_scholarship" boolean NOT NULL DEFAULT false, "scholarship_percentage" double precision, "scholarship_details" text, "student_id" uuid, "section_id" uuid, "academic_year_id" uuid, CONSTRAINT "UQ_46874ff700d6ef5324c093acdeb" UNIQUE ("code"), CONSTRAINT "PK_7c0f752f9fb68bf6ed7367ab00f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."teachers_contract_type_enum" AS ENUM('full_time', 'part_time', 'temporary', 'permanent')`);
        await queryRunner.query(`CREATE TYPE "public"."teachers_labor_regime_enum" AS ENUM('public', 'private')`);
        await queryRunner.query(`CREATE TYPE "public"."teachers_workload_type_enum" AS ENUM('20_hours', '30_hours', '40_hours')`);
        await queryRunner.query(`CREATE TYPE "public"."teachers_employment_status_enum" AS ENUM('active', 'inactive', 'on_leave')`);
        await queryRunner.query(`CREATE TABLE "teachers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "teacher_code" character varying(100) NOT NULL, "specialization" character varying(100) NOT NULL, "professional_title" character varying(100) NOT NULL, "university" character varying(100) NOT NULL, "graduation_year" integer NOT NULL, "professional_license" character varying(100) NOT NULL, "contract_type" "public"."teachers_contract_type_enum" NOT NULL, "labor_regime" "public"."teachers_labor_regime_enum" NOT NULL, "hire_date" date NOT NULL, "termination_date" date, "workload_type" "public"."teachers_workload_type_enum" NOT NULL, "weekly_hours" integer NOT NULL, "teaching_level" character varying(100) NOT NULL, "employment_status" "public"."teachers_employment_status_enum" NOT NULL, "institution_id" uuid, "person_id" uuid, CONSTRAINT "PK_a8d4f83be3abe4c687b0a0093c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subject_areas_type_enum" AS ENUM('core', 'elective', 'optional')`);
        await queryRunner.query(`CREATE TYPE "public"."subject_areas_status_enum" AS ENUM('active', 'inactive', 'pending', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "subject_areas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "name" character varying(100) NOT NULL, "code" character varying(20) NOT NULL, "description" text, "type" "public"."subject_areas_type_enum" NOT NULL, "status" "public"."subject_areas_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "UQ_42067cdc5e195181b2cccca6b58" UNIQUE ("code"), CONSTRAINT "PK_bb3f9df67b26fe54dc9b003ac60" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "courses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "code" character varying(20) NOT NULL, "name" character varying(100) NOT NULL, "description" text NOT NULL, "weekly_hours" integer NOT NULL, "total_hours" integer NOT NULL, "credits" integer NOT NULL, "competencies" text NOT NULL, "is_mandatory" boolean NOT NULL, "syllabus_url" character varying(255) NOT NULL, "subject_area_id" uuid, "grade_id" uuid, CONSTRAINT "UQ_86b3589486bac01d2903e22471c" UNIQUE ("code"), CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."section_courses_modality_enum" AS ENUM('online', 'offline', 'hybrid')`);
        await queryRunner.query(`CREATE TYPE "public"."section_courses_status_enum" AS ENUM('active', 'inactive', 'pending', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "section_courses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "modality" "public"."section_courses_modality_enum" NOT NULL, "max_students" integer NOT NULL, "enrolled_students" integer NOT NULL, "status" "public"."section_courses_status_enum" NOT NULL, "academic_year_id" uuid, "sectionId" uuid, "courseId" uuid, CONSTRAINT "PK_f2941cc75f865915f2ac1534efb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."virtual_classrooms_platform_enum" AS ENUM('zoom', 'google_meet', 'microsoft_teams')`);
        await queryRunner.query(`CREATE TYPE "public"."virtual_classrooms_type_enum" AS ENUM('lecture', 'workshop', 'meeting')`);
        await queryRunner.query(`CREATE TYPE "public"."virtual_classrooms_status_enum" AS ENUM('active', 'inactive', 'pending', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "virtual_classrooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "platform" "public"."virtual_classrooms_platform_enum" NOT NULL, "access_url" text NOT NULL, "access_code" text NOT NULL, "access_password" text NOT NULL, "type" "public"."virtual_classrooms_type_enum" NOT NULL, "meeting_id" text NOT NULL, "settings" jsonb, "status" "public"."virtual_classrooms_status_enum" NOT NULL DEFAULT 'active', "section_course_id" uuid, CONSTRAINT "PK_c7daa8b2dfd7c9234da357fcbbc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."teacher_attendances_status_enum" AS ENUM('present', 'absent', 'late', 'excused')`);
        await queryRunner.query(`CREATE TABLE "teacher_attendances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "date" date NOT NULL, "check_in_time" TIME NOT NULL, "check_out_time" TIME, "status" "public"."teacher_attendances_status_enum" NOT NULL, "leave_type" character varying(100) NOT NULL, "reason" text, "observations" text, "supporting_documents" text, "teacher_id" uuid, CONSTRAINT "PK_f96e2c5a59fee6f2e79c7083166" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."student_observations_type_enum" AS ENUM('behavioral', 'academic', 'social')`);
        await queryRunner.query(`CREATE TABLE "student_observations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "date" date NOT NULL, "observation" text NOT NULL, "type" "public"."student_observations_type_enum" NOT NULL, "follow_up" text NOT NULL, "referral" text NOT NULL, "is_confidential" boolean NOT NULL DEFAULT false, "student_id" uuid, "teacher_id" uuid, CONSTRAINT "PK_46d26cade3377fcd051397332a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."guardians_relationship_enum" AS ENUM('parent', 'guardian', 'other')`);
        await queryRunner.query(`CREATE TABLE "guardians" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "occupation" character varying(100) NOT NULL, "workplace" character varying(100) NOT NULL, "workplace_address" text NOT NULL, "workplace_phone" text NOT NULL, "education_level" character varying(100) NOT NULL, "monthly_income" integer NOT NULL, "lives_with_student" boolean NOT NULL, "is_primary_guardian" boolean NOT NULL, "relationship" "public"."guardians_relationship_enum" NOT NULL, "person_id" uuid, CONSTRAINT "PK_3dcf02f3dc96a2c017106f280be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_guardians" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_primary" boolean NOT NULL, "pickup_authorization" boolean NOT NULL, "receives_notifications" text, "emergency_contact" boolean NOT NULL, "student_id" uuid, "guardian_id" uuid, CONSTRAINT "PK_11ef78f5131711d8da1b14e3332" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "session_token" character varying(255) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "last_active" TIMESTAMP NOT NULL, "user_agent" character varying(255) NOT NULL, "ip_address" character varying(45) NOT NULL, "user_id" uuid, CONSTRAINT "UQ_f10db2949bbea55b44f31108e1a" UNIQUE ("session_token"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."schedules_day_of_week_enum" AS ENUM('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday')`);
        await queryRunner.query(`CREATE TABLE "schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "title" character varying(255) NOT NULL, "day_of_week" "public"."schedules_day_of_week_enum" NOT NULL, "description" text NOT NULL, "start_at" TIME WITH TIME ZONE NOT NULL, "end_at" TIME WITH TIME ZONE NOT NULL, "classroom" character varying(255) NOT NULL, "section_course_id" uuid, CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_method_enum" AS ENUM('cash', 'credit_card', 'debit_card', 'bank_transfer', 'mobile_payment', 'yape', 'plin')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'completed', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "concept" text NOT NULL, "installment_number" integer NOT NULL, "amount" numeric(10,2) NOT NULL, "due_date" date NOT NULL, "payment_date" date NOT NULL, "amount_paid" numeric(10,2) NOT NULL, "payment_method" "public"."payments_payment_method_enum" NOT NULL, "receipt_number" character varying(50) NOT NULL, "status" "public"."payments_status_enum" NOT NULL, "late_fee" numeric(10,2) NOT NULL DEFAULT '0', "observations" text, "payer_name" character varying(100) NOT NULL, "enrollment_id_id" uuid, CONSTRAINT "UQ_a6659e5eb1bf3b467c819e7f167" UNIQUE ("receipt_number"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('info', 'warning', 'alert', 'success', 'error')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "title" character varying(255) NOT NULL, "content" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "link_url" character varying(255), "send_at" TIME WITH TIME ZONE NOT NULL, "read_at" TIME WITH TIME ZONE, "type" "public"."notifications_type_enum" NOT NULL, "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'medium', "recipient_id" character varying(36) NOT NULL, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "learning_modules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "title" character varying(100) NOT NULL, "description" text NOT NULL, "display_order" integer NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "is_published" boolean NOT NULL, "section_course_id_id" uuid, CONSTRAINT "PK_5884364b4820dc6ee536d3f65ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."learning_materials_type_enum" AS ENUM('video', 'document', 'audio', 'presentation', 'other')`);
        await queryRunner.query(`CREATE TABLE "learning_materials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "title" text NOT NULL, "type" "public"."learning_materials_type_enum" NOT NULL, "description" text NOT NULL, "url" text NOT NULL, "duration_minutes" integer NOT NULL DEFAULT '0', "thumbnail" text NOT NULL, "view_count" integer NOT NULL DEFAULT '0', "like_count" integer NOT NULL DEFAULT '0', "dislike_count" integer NOT NULL DEFAULT '0', "is_visible" boolean NOT NULL DEFAULT true, "download_enabled" boolean NOT NULL DEFAULT false, "display_order" integer NOT NULL DEFAULT '0', "section_course_id" uuid, "module_id" uuid, "teacher_id" uuid, CONSTRAINT "PK_ae1ef944b64d9645383c5cc6da0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."forums_type_enum" AS ENUM('public', 'private')`);
        await queryRunner.query(`CREATE TYPE "public"."forums_moderation_level_enum" AS ENUM('none', 'low', 'high')`);
        await queryRunner.query(`CREATE TYPE "public"."forums_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "forums" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "title" text NOT NULL, "type" "public"."forums_type_enum" NOT NULL, "description" text NOT NULL, "is_moderated" boolean NOT NULL DEFAULT false, "allow_anonymous_posts" boolean NOT NULL DEFAULT true, "max_post_length" integer NOT NULL DEFAULT '0', "moderation_level" "public"."forums_moderation_level_enum" NOT NULL DEFAULT 'none', "status" "public"."forums_status_enum" NOT NULL DEFAULT 'active', "section_course_id" uuid, "module_id" uuid, CONSTRAINT "PK_d6395f83d095751ecc4068fb040" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."grade_levels_level_enum" AS ENUM('primary', 'secondary', 'higher')`);
        await queryRunner.query(`CREATE TABLE "grade_levels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "level" "public"."grade_levels_level_enum" NOT NULL, "grade_number" integer NOT NULL, "name" character varying(100) NOT NULL, "description" text NOT NULL, "max_capacity" integer NOT NULL, "institution_id" uuid, CONSTRAINT "PK_6acd477de8b53978fc389479713" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "forum_threads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "title" text NOT NULL, "content" text NOT NULL, "is_pinned" boolean NOT NULL DEFAULT true, "reply_count" integer NOT NULL DEFAULT '0', "is_locked" boolean NOT NULL DEFAULT false, "view_count" integer NOT NULL DEFAULT '0', "user_id" uuid, "forum_id" uuid, CONSTRAINT "PK_38ce39ab347624dee46e0d11e95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "forum_posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "content" text NOT NULL, "attachment_url" text NOT NULL, "likes" integer NOT NULL DEFAULT '0', "is_solution" boolean NOT NULL DEFAULT false, "parent_post_id" uuid, "forum_thread_id" uuid, "user_id" uuid, CONSTRAINT "PK_3e9c301114a0fd42c998681b04e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."email_logs_status_enum" AS ENUM('sent', 'failed')`);
        await queryRunner.query(`CREATE TABLE "email_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "recipient" text NOT NULL, "subject" text NOT NULL, "body" text NOT NULL, "status" "public"."email_logs_status_enum" NOT NULL, "user_id" uuid, CONSTRAINT "PK_999382218924e953a790d340571" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "competencies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "code" character varying(20) NOT NULL, "name" character varying(100) NOT NULL, "description" text NOT NULL, "expected_achievement" text NOT NULL, "course_id" uuid, CONSTRAINT "UQ_587d3b9969cac4d2fce8540d7b6" UNIQUE ("code"), CONSTRAINT "PK_0b29ecda233cc61de0d93527813" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."chat_rooms_type_enum" AS ENUM('private', 'group')`);
        await queryRunner.query(`CREATE TABLE "chat_rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "name" character varying(100) NOT NULL, "type" "public"."chat_rooms_type_enum" NOT NULL, "description" character varying(255), "max_members" integer, "is_active" boolean NOT NULL DEFAULT true, "section_course_id" uuid, CONSTRAINT "PK_c69082bd83bffeb71b0f455bd59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."chat_participants_role_enum" AS ENUM('admin', 'member')`);
        await queryRunner.query(`CREATE TABLE "chat_participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "join_date" TIMESTAMP NOT NULL, "last_read_at" TIMESTAMP, "is_muted" boolean NOT NULL DEFAULT false, "role" "public"."chat_participants_role_enum" NOT NULL, "chat_room_id" uuid, "user_id" uuid, CONSTRAINT "PK_ebf68c52a2b4dceb777672b782d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_type_enum" AS ENUM('text', 'image', 'video')`);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "content" text NOT NULL, "type" "public"."chat_messages_type_enum" NOT NULL, "file_url" text NOT NULL, "file_name" text NOT NULL, "file_size_mb" double precision NOT NULL, "is_edited" boolean NOT NULL DEFAULT false, "reply_to_id" uuid, "chat_room_id" uuid, "user_id" uuid, CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."behavior_records_type_enum" AS ENUM('positive', 'negative')`);
        await queryRunner.query(`CREATE TYPE "public"."behavior_records_severity_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`CREATE TABLE "behavior_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "type" "public"."behavior_records_type_enum" NOT NULL, "category" character varying(100) NOT NULL, "description" text NOT NULL, "record_date" date NOT NULL, "severity" "public"."behavior_records_severity_enum" NOT NULL, "action_token" character varying(100) NOT NULL, "guardian_notified" boolean NOT NULL DEFAULT false, "notification_date" date, "student_id" uuid, "period_id" uuid, "teacher_id" uuid, CONSTRAINT "PK_6b7fd1dccc95dfad03e80cee400" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendances_session_type_enum" AS ENUM('lecture', 'lab', 'seminar', 'workshop')`);
        await queryRunner.query(`CREATE TYPE "public"."attendances_status_enum" AS ENUM('present', 'absent', 'late', 'excused')`);
        await queryRunner.query(`CREATE TABLE "attendances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "date" date NOT NULL, "session_type" "public"."attendances_session_type_enum" NOT NULL, "status" "public"."attendances_status_enum" NOT NULL, "check_in_time" TIME NOT NULL, "check_out_time" TIME, "observations" text, "justification_document" text, "justification" text, "enrollment_id" uuid, "section_course_id" uuid, CONSTRAINT "PK_483ed97cd4cd43ab4a117516b69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assigments_type_enum" AS ENUM('homework', 'project', 'quiz', 'exam')`);
        await queryRunner.query(`CREATE TYPE "public"."assigments_status_enum" AS ENUM('draft', 'published', 'closed')`);
        await queryRunner.query(`CREATE TABLE "assigments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "title" character varying(100) NOT NULL, "description" text NOT NULL, "instructions" text NOT NULL, "max_score" integer NOT NULL, "assigned_date" TIMESTAMP WITH TIME ZONE NOT NULL, "due_date" TIMESTAMP WITH TIME ZONE NOT NULL, "late_submission_allowed" boolean NOT NULL, "late_penalty_percentage" integer NOT NULL, "type" "public"."assigments_type_enum" NOT NULL, "max_file_size_mb" integer NOT NULL, "allowed_file_types" text NOT NULL, "max_attempts" integer NOT NULL, "group_assignment" boolean NOT NULL, "rubric_url" character varying(255) NOT NULL, "status" "public"."assigments_status_enum" NOT NULL, "section_course_id" uuid, "teacher_id" uuid, "module_id" uuid, CONSTRAINT "PK_0714b068663422df73b21352daa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assigment_submissions_status_enum" AS ENUM('pending', 'graded', 'late')`);
        await queryRunner.query(`CREATE TABLE "assigment_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "attempt_number" integer NOT NULL, "submission_date" TIMESTAMP NOT NULL, "submission_text" text NOT NULL, "file_url" character varying(255) NOT NULL, "file_name" character varying(255) NOT NULL, "link_url" character varying(255) NOT NULL, "score" integer NOT NULL, "feedback" text NOT NULL, "feedback_date" TIMESTAMP NOT NULL, "feedback_file_url" character varying(255) NOT NULL, "graded_by" character varying(255) NOT NULL, "graded_at" TIMESTAMP NOT NULL, "status" "public"."assigment_submissions_status_enum" NOT NULL, "assigment_id" uuid, CONSTRAINT "PK_342067b8a87eca3dd4eb1ccea18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assessments_type_enum" AS ENUM('formative', 'summative', 'diagnostic')`);
        await queryRunner.query(`CREATE TYPE "public"."assessments_status_enum" AS ENUM('pending', 'completed', 'reviewed')`);
        await queryRunner.query(`CREATE TABLE "assessments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "name" character varying(100) NOT NULL, "description" text NOT NULL, "assessment_date" date NOT NULL, "weight_percentage" integer NOT NULL, "max_score" integer NOT NULL, "type" "public"."assessments_type_enum" NOT NULL, "status" "public"."assessments_status_enum" NOT NULL, "period_id" uuid, "section_course_id" uuid, CONSTRAINT "PK_a3442bd80a00e9111cefca57f6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assessment_scores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "score" numeric(5,2) NOT NULL, "observation" character varying(255) NOT NULL, "register_at" TIMESTAMP WITH TIME ZONE NOT NULL, "enrollment_id" uuid, "assessment_id" uuid, CONSTRAINT "PK_e4ff9a378c0bffd01452253a5da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."announcements_recipient_enum" AS ENUM('students', 'teachers', 'all')`);
        await queryRunner.query(`CREATE TYPE "public"."announcements_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TYPE "public"."announcements_status_enum" AS ENUM('draft', 'published', 'expired')`);
        await queryRunner.query(`CREATE TABLE "announcements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "title" character varying(150) NOT NULL, "content" text NOT NULL, "recipient" "public"."announcements_recipient_enum" NOT NULL, "published_at" TIMESTAMP WITH TIME ZONE NOT NULL, "expire_at" TIMESTAMP WITH TIME ZONE NOT NULL, "attachment_url" character varying(255) NOT NULL, "priority" "public"."announcements_priority_enum" NOT NULL, "status" "public"."announcements_status_enum" NOT NULL, "view" integer NOT NULL, "user_id" uuid, "grade_id" uuid, CONSTRAINT "PK_b3ad760876ff2e19d58e05dc8b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profile_picture"`);
        await queryRunner.query(`ALTER TABLE "academic_periods" DROP COLUMN "academic_year_id"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP COLUMN "grade_id"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "shift"`);
        await queryRunner.query(`DROP TYPE "public"."grades_shift_enum"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "academic_year_id"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP CONSTRAINT "UQ_aed8f750101d1f10aa3d6f78024"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "failed_login_attempts" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "academic_periods" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "academic_periods" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "academic_periods" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "academic_periods" ADD "period_number" integer NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."academic_periods_type_enum" AS ENUM('monthly', 'bimonthly', 'quarterly', 'semester', 'annual')`);
        await queryRunner.query(`ALTER TABLE "academic_periods" ADD "type" "public"."academic_periods_type_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."academic_periods_status_enum" AS ENUM('planned', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "academic_periods" ADD "status" "public"."academic_periods_status_enum" NOT NULL DEFAULT 'planned'`);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."academic_years_modality_enum" AS ENUM('in-person', 'online', 'hybrid')`);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD "modality" "public"."academic_years_modality_enum" NOT NULL DEFAULT 'in-person'`);
        await queryRunner.query(`CREATE TYPE "public"."academic_years_grading_system_enum" AS ENUM('percentage', 'letter', 'gpa')`);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD "grading_system" "public"."academic_years_grading_system_enum" NOT NULL DEFAULT 'percentage'`);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD "passing_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD "passing_grade" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD "academic_calendar_url" character varying(255) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."academic_years_status_enum" AS ENUM('planned', 'ongoing', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD "status" "public"."academic_years_status_enum" NOT NULL DEFAULT 'planned'`);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD "institution_id" uuid`);
        await queryRunner.query(`ALTER TABLE "sections" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sections" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sections" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`CREATE TYPE "public"."sections_status_enum" AS ENUM('active', 'inactive', 'pending', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "sections" ADD "status" "public"."sections_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`CREATE TYPE "public"."sections_shift_enum" AS ENUM('morning', 'afternoon', 'evening')`);
        await queryRunner.query(`ALTER TABLE "sections" ADD "shift" "public"."sections_shift_enum" NOT NULL DEFAULT 'morning'`);
        await queryRunner.query(`ALTER TABLE "sections" ADD "tutor" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sections" ADD "classroom" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sections" ADD "available_slots" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sections" ADD "year_academic_id" uuid`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "cumulative_grade" numeric(5,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "exam_grade" numeric(5,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "final_grade" numeric(5,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "tardies" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "absences" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "observations" text`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "modified_by" character varying(100) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."grades_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "status" "public"."grades_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "enrollment_id" uuid`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "section_course_id" uuid`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "period_id" uuid`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "teacher_id" uuid`);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD CONSTRAINT "FK_232b0e9f48e6d90331176cb4855" FOREIGN KEY ("institution_id") REFERENCES "institutions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "FK_9fb1f13ef6bf5fa772c292fb546" FOREIGN KEY ("year_academic_id") REFERENCES "academic_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_97305c8aa21f2cabd3963e4e105" FOREIGN KEY ("institution_id") REFERENCES "institutions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_5dffbda00c34ee406d6abccbc59" FOREIGN KEY ("person_id") REFERENCES "persons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_307813fe255896d6ebf3e6cd55c" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_ebbb1eaa243b6fd10a61fe38c78" FOREIGN KEY ("section_id") REFERENCES "sections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_1b48da02d1615a115333362b7c4" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teachers" ADD CONSTRAINT "FK_7e4f14e621b7b9f65fb9cd1d140" FOREIGN KEY ("institution_id") REFERENCES "institutions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teachers" ADD CONSTRAINT "FK_619d084d25c33948e2f1c040475" FOREIGN KEY ("person_id") REFERENCES "persons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grades" ADD CONSTRAINT "FK_ce4136a5756d2fe2ee20fe01a3d" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grades" ADD CONSTRAINT "FK_df0f86e3ee03ffe6350939ac126" FOREIGN KEY ("section_course_id") REFERENCES "section_courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grades" ADD CONSTRAINT "FK_9cead70150ec5e0797ae8896845" FOREIGN KEY ("period_id") REFERENCES "academic_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grades" ADD CONSTRAINT "FK_4e40960913bb4a4c059fa9939d6" FOREIGN KEY ("teacher_id") REFERENCES "academic_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_f2341a32e4cc09be0946be112f2" FOREIGN KEY ("subject_area_id") REFERENCES "subject_areas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_8cf3e66aec03331d89f46fff9fb" FOREIGN KEY ("grade_id") REFERENCES "grades"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "section_courses" ADD CONSTRAINT "FK_ece412143cffa80586ac2e16cd5" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "section_courses" ADD CONSTRAINT "FK_886417d859c55821b3cfddfaf96" FOREIGN KEY ("sectionId") REFERENCES "sections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "section_courses" ADD CONSTRAINT "FK_320e1d65472f54ac1c8f53cdb56" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "virtual_classrooms" ADD CONSTRAINT "FK_3f816652b701c9b9685ff385b63" FOREIGN KEY ("section_course_id") REFERENCES "section_courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_attendances" ADD CONSTRAINT "FK_dd8b3453aee715ac549fcff7492" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_observations" ADD CONSTRAINT "FK_5c5a539e21a7e5d5a5f47ff8a7b" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_observations" ADD CONSTRAINT "FK_dd484d822868e65596b438fc8e2" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guardians" ADD CONSTRAINT "FK_ffc18ba44911d3357b476117bab" FOREIGN KEY ("person_id") REFERENCES "persons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_guardians" ADD CONSTRAINT "FK_8194052bdd62204f061dd44e0c9" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_guardians" ADD CONSTRAINT "FK_ec3cd56a2093be19f778af57c63" FOREIGN KEY ("guardian_id") REFERENCES "guardians"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_e29076c2b8285c832bbe226febf" FOREIGN KEY ("section_course_id") REFERENCES "section_courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_53fcd675c6a3146de807c1e5138" FOREIGN KEY ("enrollment_id_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "learning_modules" ADD CONSTRAINT "FK_9f89b56332a1fb88e59b13fa863" FOREIGN KEY ("section_course_id_id") REFERENCES "section_courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "learning_materials" ADD CONSTRAINT "FK_b11330d56a193c6202f3c71b579" FOREIGN KEY ("section_course_id") REFERENCES "section_courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "learning_materials" ADD CONSTRAINT "FK_4267945bcf48ff2a49e2a59a7ab" FOREIGN KEY ("module_id") REFERENCES "learning_modules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "learning_materials" ADD CONSTRAINT "FK_32e7a2b40c9c54f56f2790bbac4" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forums" ADD CONSTRAINT "FK_10ad4406d2e8a0fd249c9fb7b5d" FOREIGN KEY ("section_course_id") REFERENCES "section_courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forums" ADD CONSTRAINT "FK_afaebca9df2e633fe94ba75e09e" FOREIGN KEY ("module_id") REFERENCES "learning_modules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grade_levels" ADD CONSTRAINT "FK_217dad506f097e36d240e2184a7" FOREIGN KEY ("institution_id") REFERENCES "institutions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_threads" ADD CONSTRAINT "FK_83a816d21e76c7c1b4c4c14283f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_threads" ADD CONSTRAINT "FK_1f86d329b35e813315cbcac8b37" FOREIGN KEY ("forum_id") REFERENCES "forums"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_posts" ADD CONSTRAINT "FK_927df00bfdb6dfe958f75c20196" FOREIGN KEY ("parent_post_id") REFERENCES "forum_posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_posts" ADD CONSTRAINT "FK_43b158f3b772422a3f49459cffc" FOREIGN KEY ("forum_thread_id") REFERENCES "forum_threads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_posts" ADD CONSTRAINT "FK_28e52f36bde02d737dba6911f37" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_logs" ADD CONSTRAINT "FK_6ba496025b5d542b84976162e18" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competencies" ADD CONSTRAINT "FK_2b4e3bc361546035c0a53cb301b" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_rooms" ADD CONSTRAINT "FK_6186624ec3758638531cfd19a9c" FOREIGN KEY ("section_course_id") REFERENCES "section_courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participants" ADD CONSTRAINT "FK_d04f6115f51cd8fd8551320dd02" FOREIGN KEY ("chat_room_id") REFERENCES "chat_rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participants" ADD CONSTRAINT "FK_b4129b3e21906ca57b503a1d834" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_46d19cf514d5c46a1f15598cf1c" FOREIGN KEY ("reply_to_id") REFERENCES "chat_messages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_3217ec6230770d4d2c826fc0380" FOREIGN KEY ("chat_room_id") REFERENCES "chat_rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_5588b6cea298cedec7063c0d33e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "behavior_records" ADD CONSTRAINT "FK_25996bbc4284db4223ea9247a30" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "behavior_records" ADD CONSTRAINT "FK_8fca3a475c361e830c6eb4f47d9" FOREIGN KEY ("period_id") REFERENCES "academic_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "behavior_records" ADD CONSTRAINT "FK_8eb6402f99583d3a932555d5e52" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD CONSTRAINT "FK_0104118862debb834ec7c358ad6" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD CONSTRAINT "FK_c6c8726419a6b0fc4adc98543dd" FOREIGN KEY ("section_course_id") REFERENCES "section_courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assigments" ADD CONSTRAINT "FK_47c58bebe4cb01be4e3b1111372" FOREIGN KEY ("section_course_id") REFERENCES "section_courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assigments" ADD CONSTRAINT "FK_e9c8825006531963015144592ff" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assigments" ADD CONSTRAINT "FK_584e111c8fe8d73f5546fe9e33b" FOREIGN KEY ("module_id") REFERENCES "learning_modules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assigment_submissions" ADD CONSTRAINT "FK_ce1ff6e08d639ef06e3900a657d" FOREIGN KEY ("assigment_id") REFERENCES "assigments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_a98d56a97449127311cca42e598" FOREIGN KEY ("period_id") REFERENCES "academic_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_de592e45552c6c5f610eb1a05bf" FOREIGN KEY ("section_course_id") REFERENCES "section_courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessment_scores" ADD CONSTRAINT "FK_7e9aae73b6c437467997d63bbe4" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessment_scores" ADD CONSTRAINT "FK_3960c2c632d88420fed7f03b683" FOREIGN KEY ("assessment_id") REFERENCES "assessments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_2e02da2019c7fcdbbd5d30b6816" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_7f0c544c2090f4278147a285d7b" FOREIGN KEY ("grade_id") REFERENCES "grades"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_7f0c544c2090f4278147a285d7b"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_2e02da2019c7fcdbbd5d30b6816"`);
        await queryRunner.query(`ALTER TABLE "assessment_scores" DROP CONSTRAINT "FK_3960c2c632d88420fed7f03b683"`);
        await queryRunner.query(`ALTER TABLE "assessment_scores" DROP CONSTRAINT "FK_7e9aae73b6c437467997d63bbe4"`);
        await queryRunner.query(`ALTER TABLE "assessments" DROP CONSTRAINT "FK_de592e45552c6c5f610eb1a05bf"`);
        await queryRunner.query(`ALTER TABLE "assessments" DROP CONSTRAINT "FK_a98d56a97449127311cca42e598"`);
        await queryRunner.query(`ALTER TABLE "assigment_submissions" DROP CONSTRAINT "FK_ce1ff6e08d639ef06e3900a657d"`);
        await queryRunner.query(`ALTER TABLE "assigments" DROP CONSTRAINT "FK_584e111c8fe8d73f5546fe9e33b"`);
        await queryRunner.query(`ALTER TABLE "assigments" DROP CONSTRAINT "FK_e9c8825006531963015144592ff"`);
        await queryRunner.query(`ALTER TABLE "assigments" DROP CONSTRAINT "FK_47c58bebe4cb01be4e3b1111372"`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP CONSTRAINT "FK_c6c8726419a6b0fc4adc98543dd"`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP CONSTRAINT "FK_0104118862debb834ec7c358ad6"`);
        await queryRunner.query(`ALTER TABLE "behavior_records" DROP CONSTRAINT "FK_8eb6402f99583d3a932555d5e52"`);
        await queryRunner.query(`ALTER TABLE "behavior_records" DROP CONSTRAINT "FK_8fca3a475c361e830c6eb4f47d9"`);
        await queryRunner.query(`ALTER TABLE "behavior_records" DROP CONSTRAINT "FK_25996bbc4284db4223ea9247a30"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_5588b6cea298cedec7063c0d33e"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_3217ec6230770d4d2c826fc0380"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_46d19cf514d5c46a1f15598cf1c"`);
        await queryRunner.query(`ALTER TABLE "chat_participants" DROP CONSTRAINT "FK_b4129b3e21906ca57b503a1d834"`);
        await queryRunner.query(`ALTER TABLE "chat_participants" DROP CONSTRAINT "FK_d04f6115f51cd8fd8551320dd02"`);
        await queryRunner.query(`ALTER TABLE "chat_rooms" DROP CONSTRAINT "FK_6186624ec3758638531cfd19a9c"`);
        await queryRunner.query(`ALTER TABLE "competencies" DROP CONSTRAINT "FK_2b4e3bc361546035c0a53cb301b"`);
        await queryRunner.query(`ALTER TABLE "email_logs" DROP CONSTRAINT "FK_6ba496025b5d542b84976162e18"`);
        await queryRunner.query(`ALTER TABLE "forum_posts" DROP CONSTRAINT "FK_28e52f36bde02d737dba6911f37"`);
        await queryRunner.query(`ALTER TABLE "forum_posts" DROP CONSTRAINT "FK_43b158f3b772422a3f49459cffc"`);
        await queryRunner.query(`ALTER TABLE "forum_posts" DROP CONSTRAINT "FK_927df00bfdb6dfe958f75c20196"`);
        await queryRunner.query(`ALTER TABLE "forum_threads" DROP CONSTRAINT "FK_1f86d329b35e813315cbcac8b37"`);
        await queryRunner.query(`ALTER TABLE "forum_threads" DROP CONSTRAINT "FK_83a816d21e76c7c1b4c4c14283f"`);
        await queryRunner.query(`ALTER TABLE "grade_levels" DROP CONSTRAINT "FK_217dad506f097e36d240e2184a7"`);
        await queryRunner.query(`ALTER TABLE "forums" DROP CONSTRAINT "FK_afaebca9df2e633fe94ba75e09e"`);
        await queryRunner.query(`ALTER TABLE "forums" DROP CONSTRAINT "FK_10ad4406d2e8a0fd249c9fb7b5d"`);
        await queryRunner.query(`ALTER TABLE "learning_materials" DROP CONSTRAINT "FK_32e7a2b40c9c54f56f2790bbac4"`);
        await queryRunner.query(`ALTER TABLE "learning_materials" DROP CONSTRAINT "FK_4267945bcf48ff2a49e2a59a7ab"`);
        await queryRunner.query(`ALTER TABLE "learning_materials" DROP CONSTRAINT "FK_b11330d56a193c6202f3c71b579"`);
        await queryRunner.query(`ALTER TABLE "learning_modules" DROP CONSTRAINT "FK_9f89b56332a1fb88e59b13fa863"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_53fcd675c6a3146de807c1e5138"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_e29076c2b8285c832bbe226febf"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "student_guardians" DROP CONSTRAINT "FK_ec3cd56a2093be19f778af57c63"`);
        await queryRunner.query(`ALTER TABLE "student_guardians" DROP CONSTRAINT "FK_8194052bdd62204f061dd44e0c9"`);
        await queryRunner.query(`ALTER TABLE "guardians" DROP CONSTRAINT "FK_ffc18ba44911d3357b476117bab"`);
        await queryRunner.query(`ALTER TABLE "student_observations" DROP CONSTRAINT "FK_dd484d822868e65596b438fc8e2"`);
        await queryRunner.query(`ALTER TABLE "student_observations" DROP CONSTRAINT "FK_5c5a539e21a7e5d5a5f47ff8a7b"`);
        await queryRunner.query(`ALTER TABLE "teacher_attendances" DROP CONSTRAINT "FK_dd8b3453aee715ac549fcff7492"`);
        await queryRunner.query(`ALTER TABLE "virtual_classrooms" DROP CONSTRAINT "FK_3f816652b701c9b9685ff385b63"`);
        await queryRunner.query(`ALTER TABLE "section_courses" DROP CONSTRAINT "FK_320e1d65472f54ac1c8f53cdb56"`);
        await queryRunner.query(`ALTER TABLE "section_courses" DROP CONSTRAINT "FK_886417d859c55821b3cfddfaf96"`);
        await queryRunner.query(`ALTER TABLE "section_courses" DROP CONSTRAINT "FK_ece412143cffa80586ac2e16cd5"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_8cf3e66aec03331d89f46fff9fb"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_f2341a32e4cc09be0946be112f2"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP CONSTRAINT "FK_4e40960913bb4a4c059fa9939d6"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP CONSTRAINT "FK_9cead70150ec5e0797ae8896845"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP CONSTRAINT "FK_df0f86e3ee03ffe6350939ac126"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP CONSTRAINT "FK_ce4136a5756d2fe2ee20fe01a3d"`);
        await queryRunner.query(`ALTER TABLE "teachers" DROP CONSTRAINT "FK_619d084d25c33948e2f1c040475"`);
        await queryRunner.query(`ALTER TABLE "teachers" DROP CONSTRAINT "FK_7e4f14e621b7b9f65fb9cd1d140"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_1b48da02d1615a115333362b7c4"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_ebbb1eaa243b6fd10a61fe38c78"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_307813fe255896d6ebf3e6cd55c"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_5dffbda00c34ee406d6abccbc59"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_97305c8aa21f2cabd3963e4e105"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "FK_9fb1f13ef6bf5fa772c292fb546"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP CONSTRAINT "FK_232b0e9f48e6d90331176cb4855"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "period_id"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "section_course_id"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "enrollment_id"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."grades_status_enum"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "modified_by"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "observations"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "absences"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "tardies"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "final_grade"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "exam_grade"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "cumulative_grade"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP COLUMN "year_academic_id"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP COLUMN "available_slots"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP COLUMN "classroom"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP COLUMN "tutor"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP COLUMN "shift"`);
        await queryRunner.query(`DROP TYPE "public"."sections_shift_enum"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."sections_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP COLUMN "institution_id"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."academic_years_status_enum"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP COLUMN "academic_calendar_url"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP COLUMN "passing_grade"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP COLUMN "passing_date"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP COLUMN "grading_system"`);
        await queryRunner.query(`DROP TYPE "public"."academic_years_grading_system_enum"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP COLUMN "modality"`);
        await queryRunner.query(`DROP TYPE "public"."academic_years_modality_enum"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "academic_periods" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."academic_periods_status_enum"`);
        await queryRunner.query(`ALTER TABLE "academic_periods" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."academic_periods_type_enum"`);
        await queryRunner.query(`ALTER TABLE "academic_periods" DROP COLUMN "period_number"`);
        await queryRunner.query(`ALTER TABLE "academic_periods" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "academic_periods" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "academic_periods" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "failed_login_attempts"`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "name" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "code" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "grades" ADD CONSTRAINT "UQ_aed8f750101d1f10aa3d6f78024" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "academic_year_id" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."grades_shift_enum" AS ENUM('morning', 'afternoon', 'night')`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "shift" "public"."grades_shift_enum" NOT NULL DEFAULT 'morning'`);
        await queryRunner.query(`ALTER TABLE "sections" ADD "grade_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sections" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "academic_periods" ADD "academic_year_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profile_picture" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying(100)`);
        await queryRunner.query(`DROP TABLE "announcements"`);
        await queryRunner.query(`DROP TYPE "public"."announcements_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."announcements_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."announcements_recipient_enum"`);
        await queryRunner.query(`DROP TABLE "assessment_scores"`);
        await queryRunner.query(`DROP TABLE "assessments"`);
        await queryRunner.query(`DROP TYPE "public"."assessments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."assessments_type_enum"`);
        await queryRunner.query(`DROP TABLE "assigment_submissions"`);
        await queryRunner.query(`DROP TYPE "public"."assigment_submissions_status_enum"`);
        await queryRunner.query(`DROP TABLE "assigments"`);
        await queryRunner.query(`DROP TYPE "public"."assigments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."assigments_type_enum"`);
        await queryRunner.query(`DROP TABLE "attendances"`);
        await queryRunner.query(`DROP TYPE "public"."attendances_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."attendances_session_type_enum"`);
        await queryRunner.query(`DROP TABLE "behavior_records"`);
        await queryRunner.query(`DROP TYPE "public"."behavior_records_severity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."behavior_records_type_enum"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_type_enum"`);
        await queryRunner.query(`DROP TABLE "chat_participants"`);
        await queryRunner.query(`DROP TYPE "public"."chat_participants_role_enum"`);
        await queryRunner.query(`DROP TABLE "chat_rooms"`);
        await queryRunner.query(`DROP TYPE "public"."chat_rooms_type_enum"`);
        await queryRunner.query(`DROP TABLE "competencies"`);
        await queryRunner.query(`DROP TABLE "email_logs"`);
        await queryRunner.query(`DROP TYPE "public"."email_logs_status_enum"`);
        await queryRunner.query(`DROP TABLE "forum_posts"`);
        await queryRunner.query(`DROP TABLE "forum_threads"`);
        await queryRunner.query(`DROP TABLE "grade_levels"`);
        await queryRunner.query(`DROP TYPE "public"."grade_levels_level_enum"`);
        await queryRunner.query(`DROP TABLE "forums"`);
        await queryRunner.query(`DROP TYPE "public"."forums_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."forums_moderation_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."forums_type_enum"`);
        await queryRunner.query(`DROP TABLE "learning_materials"`);
        await queryRunner.query(`DROP TYPE "public"."learning_materials_type_enum"`);
        await queryRunner.query(`DROP TABLE "learning_modules"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "schedules"`);
        await queryRunner.query(`DROP TYPE "public"."schedules_day_of_week_enum"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TABLE "student_guardians"`);
        await queryRunner.query(`DROP TABLE "guardians"`);
        await queryRunner.query(`DROP TYPE "public"."guardians_relationship_enum"`);
        await queryRunner.query(`DROP TABLE "student_observations"`);
        await queryRunner.query(`DROP TYPE "public"."student_observations_type_enum"`);
        await queryRunner.query(`DROP TABLE "teacher_attendances"`);
        await queryRunner.query(`DROP TYPE "public"."teacher_attendances_status_enum"`);
        await queryRunner.query(`DROP TABLE "virtual_classrooms"`);
        await queryRunner.query(`DROP TYPE "public"."virtual_classrooms_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."virtual_classrooms_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."virtual_classrooms_platform_enum"`);
        await queryRunner.query(`DROP TABLE "section_courses"`);
        await queryRunner.query(`DROP TYPE "public"."section_courses_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."section_courses_modality_enum"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`DROP TABLE "subject_areas"`);
        await queryRunner.query(`DROP TYPE "public"."subject_areas_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subject_areas_type_enum"`);
        await queryRunner.query(`DROP TABLE "teachers"`);
        await queryRunner.query(`DROP TYPE "public"."teachers_employment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."teachers_workload_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."teachers_labor_regime_enum"`);
        await queryRunner.query(`DROP TYPE "public"."teachers_contract_type_enum"`);
        await queryRunner.query(`DROP TABLE "enrollments"`);
        await queryRunner.query(`DROP TYPE "public"."enrollments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."enrollments_enrollment_type_enum"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TYPE "public"."students_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."students_student_type_enum"`);
        await queryRunner.query(`DROP TABLE "institutions"`);
        await queryRunner.query(`DROP TABLE "persons"`);
        await queryRunner.query(`DROP TYPE "public"."persons_material_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."persons_gender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."persons_document_type_enum"`);
        await queryRunner.query(`ALTER TABLE "grades" ADD CONSTRAINT "FK_004fc3bfe751aeaf87f927b4a8c" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
